classdef VAnnotationsDivision < VAnnotations
% VAnnotationsDivision Object that contains initiation, division, ending, lysis and
% elongation annotation types.

% Copyright Daan Kiviet 2018-
% Version : 2017-03-07

    properties
        DEFAULT_SETTINGS =        { 'ann_class'                 , uint32(1), @VAnnotationsDivision ; ...
                                    'ann_initAnnotationIdx'     , uint32(1), 0 ; ...
                                    'ann_minPixelSpacing'       , uint32(1), 10 ; ...
                                    'ann_fontSize'              , uint32(1), 10 ; ...
                                  }
        ANNOTATION_TYPES        = { 'initiation', ...
                                    'division', ...
                                    'ending', ...
                                    'lysis', ...
                                    'elongation', ...
                                  };
        ANNOTATION_COLORS       = { [1.0 0.0 0.0], ...
                                    [0.0 1.0 0.0], ...
                                    [0.0 0.0 1.0], ...
                                    [1.0 0.0 1.0], ...
                                    [1.0 1.0 0.0], ...
                                  };
        ANNOTATION_DESCRIPTIONS = { 'Initiation of cell (first frame it occurs)', ...
                                    'Division of cell (first frame it is divided)', ...
                                    'Ending of cell (first frame it disappeared)', ...
                                    'Lysis of cell (first frame it is lysed)', ...
                                    'Elongation of cell (first frame it starts to elongate)', ...
                                  };
    end
    
    methods
        %% loading and saving %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        function obj = VAnnotationsDivision( region )
            obj@VAnnotations( region ); 
        end
    end
end
